#Workflow name
name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  tests:
    name: Unit tests

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [17, 18]
        java-distribution: ['zulu', 'adopt']

    runs-on: ${{ matrix.os }}

    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3

      #Set up JDK 17
      - name: Set up JDK with distribution ${{ matrix.java-distribution }} and version ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          cache: 'gradle'

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Test
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            ./gradlew test --tests "*"
          else 
            echo "No tests on the OS= $RUNNER_OS !"
            exit 1
          fi
        shell: bash

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Build
        run: ./gradlew build

      - name: List Build Results
        run: ls -ltr build

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.java-version == 17 }}
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
