#Workflow name
name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  build:
    name: Build Job
    
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]
        java-distribution: [ 'zulu', 'adopt' ]
    
    runs-on: ${{ matrix.os }}
    
    #Job's steps
    steps:
      - name: Build Job OS ${{ matrix.os }} Java ${{ matrix.java-distribution }} mit Version ${{ matrix.java-version }}
        run: echo "Hallo ich bin der Build Job"
      
      # Schritt 1: Repository auschecken

      # Schritt 2: Java 17 installieren

      # Schritt 3: Build mit Gradle durchführen

      # (optional) Schritt 4: Artefact hochladen
      