#Workflow name
name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  tests:
    name: Unit tests
    
    strategy:
      max-parallel: 2
      matrix:
        os: 'ubuntu-latest'
        java-version: [ 17, 18 ]
        java-distribution: [ 'zulu', 'adopt' ]
        include:
        - os: 'windows-latest'
          java-version: 19
          java-distribution: zulu
    
    runs-on: ${{ matrix.os }}
    
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3
      
      #Set up JDK 17
      - name: Set up JDK with distribution ${{ matrix.java-distribution }} and version ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      
      - name: Test
        run: |
              if [ "$RUNNER_OS" == "Windows" ]; then
                gradlew.exe test --tests "*"
              elif [ "$RUNNER_OS" == "Linux" ]; then
                ./gradlew test --tests "*"
              else 
                echo "$RUNNER_OS not supported"
                exit 1
              fi
        shell: bash
      
      - name: Build
        run: ./gradlew build
      

 #     - uses: actions/upload-artifact@v3
  #        with:
   #         name: Package
    #        path: build/libs